name: Scala CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Build project
        run: sbt "Test / compile"

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Scala project and create Docker image
        run: sbt "Docker / publishLocal"

      - name: Docker login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Tag Docker image
        run: docker tag plant-server:latest ghcr.io/keuhdall/plant-server:latest

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/keuhdall/plant-server:latest
